const datas = [
  {
    id: 1,
    group: "Jobcompetency1",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 2,
    group: "Managical & Competency2",
    type: "Managical Work Tasks",
    position: "Leaders and Manager",
  },
  {
    id: 3,
    group: "Jobcompetency3",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 4,
    group: "Jobcompetency4",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 5,
    group: "Jobcompetency5",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 6,
    group: "Jobcompetency6",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 7,
    group: "Jobcompetency7",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 8,
    group: "Jobcompetency8",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 9,
    group: "Jobcompetency9",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 10,
    group: "Jobcompetency10",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 11,
    group: "Managical & Competency11",
    type: "Managical Work Tasks",
    position: "Leaders and Manager",
  },
  {
    id: 12,
    group: "Jobcompetency12",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 13,
    group: "Jobcompetency13",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 14,
    group: "Jobcompetency14",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 15,
    group: "Jobcompetency15",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 16,
    group: "Jobcompetency16",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 17,
    group: "Jobcompetency17",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 18,
    group: "Jobcompetency18",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 19,
    group: "Managical & Competency19",
    type: "Managical Work Tasks",
    position: "Leaders and Manager",
  },
  {
    id: 20,
    group: "Jobcompetency20",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 21,
    group: "Jobcompetency21",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 22,
    group: "Jobcompetency22",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 23,
    group: "Jobcompetency23",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 24,
    group: "Jobcompetency24",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 25,
    group: "Jobcompetency25",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 26,
    group: "Jobcompetency26",
    type: "Employee Work Tasks",
    position: "Development",
  },
  {
    id: 27,
    group: "Managical & Competency27",
    type: "Managical Work Tasks",
    position: "Leaders and Manager",
  },
  {
    id: 28,
    group: "Jobcompetency28",
    type: "Employee Work Tasks",
    position: "Development",
  },
];

export { datas };
